# Generated by Django 5.2.7 on 2026-09-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_require_public_identifiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="request_fingerprint",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
    ]
