# Generated by Django 5.2.7 on 2026-09-14

import hashlib
import json
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_contact_submission_fields(apps, schema_editor):
    ContactMessage = apps.get_model("store", "ContactMessage")
    for message in ContactMessage.objects.all().iterator():
        semantic_data = {
            "name": message.name,
            "email": message.email,
            "phone": message.phone,
            "subject": message.subject,
            "message": message.message,
        }
        encoded = json.dumps(
            semantic_data,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        message.submission_id = uuid.uuid4()
        message.request_fingerprint = hashlib.sha256(encoded).hexdigest()
        message.save(update_fields=("submission_id", "request_fingerprint"))


def populate_contact_submission_events(apps, schema_editor):
    ContactMessage = apps.get_model("store", "ContactMessage")
    ContactMessageEvent = apps.get_model("store", "ContactMessageEvent")
    ContactMessageEvent.objects.bulk_create(
        [
            ContactMessageEvent(
                contact_message_id=message_id,
                event_type="submitted",
            )
            for message_id in ContactMessage.objects.values_list("pk", flat=True).iterator()
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_order_request_fingerprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    (
                        "manage_contactmessage",
                        "Can manage contact message workflow",
                    )
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": [
                    ("transition_order", "Can transition order status"),
                    ("cancel_order", "Can cancel and restock orders"),
                    ("record_order_payment", "Can record order payment"),
                    ("refund_order", "Can record order refunds"),
                ],
            },
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="request_fingerprint",
            field=models.CharField(default="", editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="submission_id",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="inventory_restocked_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_contact_submission_fields,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="submission_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("status_changed", "Status changed"),
                            ("payment_changed", "Payment changed"),
                            ("inventory_restocked", "Inventory restocked"),
                        ],
                        max_length=24,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                ("to_status", models.CharField(blank=True, max_length=12)),
                (
                    "from_payment_status",
                    models.CharField(blank=True, max_length=12),
                ),
                (
                    "to_payment_status",
                    models.CharField(blank=True, max_length=12),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="store.order",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.CreateModel(
            name="ContactMessageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("status_changed", "Status changed"),
                            ("notification_sent", "Notification sent"),
                            ("notification_failed", "Notification failed"),
                        ],
                        max_length=24,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                ("to_status", models.CharField(blank=True, max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_message_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contact_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="store.contactmessage",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.RunPython(
            populate_contact_submission_events,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="orderevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type", "inventory_restocked")),
                fields=("order", "event_type"),
                name="one_inventory_restock_event_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactmessageevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_type", "submitted")),
                fields=("contact_message", "event_type"),
                name="one_submitted_event_per_contact",
            ),
        ),
    ]
