(function () {
  var key = 'bfCart', params = new URLSearchParams(location.search), product = window.BF_PRODUCT_BY_ID && window.BF_PRODUCT_BY_ID(params.get('id'));
  var root = document.getElementById('product-root');
  function esc(s) { var d=document.createElement('div'); d.textContent=s; return d.innerHTML; }
  if (!product) { root.innerHTML='<h1>Product not found</h1><p><a href="shop2.html">Return to Shop</a></p>'; return; }
  document.title = product.name + ' | Bugless Fit'; document.getElementById('crumb-category').textContent=product.category;
  var variants = product.images.map(function(img,i){return '<button class="thumb '+(!i?'active':'')+'" data-image="'+i+'" aria-label="View image '+(i+1)+'"><img src="'+img+'" alt=""></button>';}).join('');
  function choices(type, values) { if(!values.length) return ''; return '<section class="selection"><h2>'+type+'</h2><div class="options">'+values.map(function(x,i){return '<button class="option '+(!i?'selected':'')+'" data-'+type.toLowerCase()+'="'+esc(x)+'">'+esc(x)+'</button>';}).join('')+'</div></section>'; }
  root.innerHTML='<div class="product-layout"><section class="gallery"><div class="thumbs">'+variants+'</div><div class="main-image"><img id="main-product-image" src="'+product.image+'" alt="'+esc(product.name)+'"></div></section><section class="product-info"><h1>'+esc(product.name)+'</h1><p class="sku">PRODUCT ID: '+esc(product.id)+'</p><div class="price-row"><span class="price">EGP '+product.price.toFixed(2)+'</span></div>'+(typeof product.inStock === 'boolean' ? '<p class="stock">'+(product.inStock?'In stock':'Out of stock')+'</p>' : '')+'<div class="payment"><strong>ACCEPTED PAYMENT METHODS</strong><span>Available at checkout</span></div>'+choices('Color',product.colors)+choices('Size',product.sizes)+'<section class="selection"><h2>Quantity</h2><div class="quantity"><button id="minus" aria-label="Decrease quantity">−</button><output id="quantity">1</output><button id="plus" aria-label="Increase quantity">+</button></div></section><div class="product-actions"><button class="action add" id="add-to-cart">ADD TO CART</button><button class="action buy" id="buy-now">BUY IT NOW</button></div><p class="validation" id="validation" aria-live="polite"></p><details class="accordion"><summary>DESCRIPTION</summary><p>'+esc(product.description)+'</p></details></section></div><section class="related"><h2>RELATED PRODUCTS</h2><div class="related-grid" id="related-products"></div></section>';
  var selected={ color:product.colors[0]||null, size:product.sizes[0]||null }, qty=1;
  document.querySelectorAll('.thumb').forEach(function(b){b.addEventListener('click',function(){document.getElementById('main-product-image').src=product.images[+b.dataset.image];document.querySelectorAll('.thumb').forEach(function(x){x.classList.remove('active')});b.classList.add('active');});});
  ['Color','Size'].forEach(function(type){document.querySelectorAll('[data-'+type.toLowerCase()+']').forEach(function(b){b.addEventListener('click',function(){selected[type.toLowerCase()]=b.dataset[type.toLowerCase()];document.querySelectorAll('[data-'+type.toLowerCase()+']').forEach(function(x){x.classList.remove('selected')});b.classList.add('selected');});});});
  function setQty(next){qty=Math.max(1,next);document.getElementById('quantity').textContent=qty;} document.getElementById('minus').onclick=function(){setQty(qty-1)};document.getElementById('plus').onclick=function(){setQty(qty+1)};
  function cart(){try{return JSON.parse(localStorage.getItem(key))||[]}catch(e){return[]}} function save(items){localStorage.setItem(key,JSON.stringify(items));renderCart();} function add(){var items=cart(), match=items.filter(function(i){return i.id===product.id&&i.color===selected.color&&i.size===selected.size})[0];if(match)match.qty+=qty;else items.push({id:product.id,name:product.name,price:product.price,qty:qty,color:selected.color,size:selected.size,image:product.image});save(items);return true;}
  document.getElementById('add-to-cart').onclick=function(){if(add())document.getElementById('validation').textContent='Added to your cart.'}; document.getElementById('buy-now').onclick=function(){if(add())location.href='checkout.html'};
  var related=window.BF_PRODUCTS.filter(function(p){return p.category===product.category&&p.id!==product.id}).slice(0,4); if(related.length<4) related=related.concat(window.BF_PRODUCTS.filter(function(p){return p.id!==product.id&&p.category!==product.category}).slice(0,4-related.length)); document.getElementById('related-products').innerHTML=related.map(function(p){return '<a class="related-card" href="product.html?id='+encodeURIComponent(p.id)+'"><img src="'+p.image+'" alt="'+esc(p.name)+'"><h3>'+esc(p.name)+'</h3><p>EGP '+p.price.toFixed(2)+'</p></a>';}).join('');
  var panel=document.getElementById('cart');document.getElementById('cart-toggle-btn').onclick=function(){panel.classList.toggle('cart-open')};document.getElementById('clear-cart-btn').onclick=function(){save([])};document.getElementById('checkout-btn').onclick=function(){location.href='checkout.html'};
  function renderCart(){var items=cart(), total=0,count=0, list=document.getElementById('cart-items');list.innerHTML=items.map(function(i,index){total+=i.price*i.qty;count+=i.qty;return '<div class="cart-item"><span>'+esc(i.name)+(i.size?' · '+esc(i.size):'')+'</span><span>'+i.qty+' × EGP '+i.price.toFixed(2)+'</span><button class="remove-btn" data-remove="'+index+'" aria-label="Remove item">×</button></div>';}).join('');document.getElementById('cart-total').textContent=total.toFixed(2);document.getElementById('cart-count-badge').textContent=count;list.querySelectorAll('[data-remove]').forEach(function(b){b.onclick=function(){var items=cart();items.splice(+b.dataset.remove,1);save(items)}});} renderCart();
  var burger=document.getElementById('burger'), menu=document.getElementById('menu');burger.onclick=function(){burger.classList.toggle('is-active');menu.classList.toggle('is-active')}; document.getElementById('product-search').onsubmit=function(e){e.preventDefault();var q=this.querySelector('input').value.trim();location.href='shop2.html'+(q?'?search='+encodeURIComponent(q):'')};
})();
